---
- name: Installation de Prérequis AWX
  apt:
    update_cache: yes
    name:
      - make
      - curl
      - sudo
      - net-tools
      - git
      - build-essential
      - jq
      - yq
      - python3
      - python3-pip
      - python3-cloudflare
      - cloud-utils
    state: latest

- name: Install Paquets Python Kubernetes
  pip:
    name:
      - setuptools
      - boto3
      - botocore
      - crypto
      - cryptography
      - kubernetes
    state: latest
    extra_args: "--break-system-packages --upgrade"